INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'DESPESAS DE ALIMENTAÇÃO');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'DESPESA DE CASA');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'DESPESAS DE CARTÃO DE CRÉDITO');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'DESPESAS DE SAÚDE');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'SALÁRIO E RENDA');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'VAIGENS E LAZER');

INSERT INTO CATEGORIA (ID, NOME)
VALUES(NEWID(), 'OUTROS');

SELECT * FROM CATEGORIA